### PR TITLE
New JOptionPane icons

### PR DESCRIPTION
**Pull request by AlexFalappa**
Altough _Nimbus_ JOptionPane icons as contributed by @granella are better than the former ugly _Metal_ icons, I feel they are a bit out of place in the Darcula LAF.

This is my proposal. What do you think?

### CODE REVIEW

**Comment by AlexFalappa** [comment]
Forgot to add a small preview:
icons

**Comment by AlexFalappa** [comment]
Please ignore my first commit (it slipped trough)

**Comment by Revivius** [comment]
well I believe they are a bit low quality, especially the question mark.

**Comment by AlexFalappa** [comment]
I see, I admit I'm no graphic designer.
Will close the pull request for now.
If I'll have time I will make a new icon set from scratch, the one above were derived from Nimbus ones.

**Pull request closed without merging**
