### PR TITLE
Allow configuration of font-name and font-size - add optionsdialog

### PR DESCRIPTION
**Pull request by markiewb**
Add sub optionspanel to tab "Appearance"
* allow to set fontname and fontsize (style is ignored, requires restart)
* default is "Dialog 12"
* font and size is used for all UI elements (whose font can be set via UIManager)
* panel is searchable via options panel search
* link to homepage

Solves also
https://github.com/Revivius/nb-darcula/issues/4 Shortcut fonts in menu have a lower size
https://github.com/Revivius/nb-darcula/issues/2 Default font is bold, but shouldn't be

2016-01-21_21h55_31

### CODE REVIEW

**Comment by Revivius** [comment]
@markiewb thank you for this! 

I will be happy to merge this but I have a couple of requests:

1. Can you please use a non editable JTextField instead of a JLabel ? Because a) it will have a standard border and b) its height will align better with the "..." button.
2. Can you align components as in following screenshot to keep consistency with current font pickers in NetBeans? Please see:
font_pickers


3. Make override checkbox disabled initially and remove empty listener methods in DarculaLAFPanel.
4. Do we need that link to homepage really ? I will feel better if you can remove the link.

Thank you for your contributions !

**Comment by markiewb** [comment]
@Revivius:
1)..4) done 
1b) -> I could not get the height correctly for all lafs, but it doesn't look too bad

Give it a try

**Comment by Revivius** [comment]
@markiewb 

I checked out your branch locally and modified a few things:

1. Align "..." button with the font text field
2. Register a PreferenceChangeListener on the NbPreference node you used to store font settings and offer user to restart the application when font settings are changed (when user clicks OK or Apply after font settings).

Please see:
restart


I want to merge your PR after those modifications but I dont know how. Should I send you a diff so that you can apply it or what ?

**Comment by markiewb** [comment]
@Revivius: Thank you for the modifications. 

Regarding the PR. I do not know what is the preferred way. So lets do it the way we already know it.
* commit your changes on a new branch Y (based on my branch X) and push it to your repo
* then merge your new branch Y into master

After that I can remove my pull-request-branch and our changes are still in the master (incl. merge history)

**Comment by Revivius** [comment]
Done!

**Comment by markiewb** [comment]
Cool! Thanks

**Pull request merged**
