### PR TITLE
Initial embedded version of default Darcula theme

### PR DESCRIPTION
**Pull request by granella**
- Install and set up the Darcula theme on first installation;
- Output, Terminal, Diff and Versioning Colors;
- Minetypes colors: css, html, javascript, plain, apache-conf, diff, el, java, json, jsp, php, properties, sql, tag, tpl, xhtml, xml

#9 partially

### CODE REVIEW

**Comment by Revivius** [comment]
@granella I have been trying your theme and modified a couple of colors but I have a problem: when I clean&build the module and run it for the first time I indeed can see Darcula profile selected in Font&Colors category but colors defined in it are not effective. See the screenshot for an example:

theme


As you can see Darcula profile is selected and Breakpoint background is [58,25,25] but it is different in editor.

If I change something in Font&Colors and apply; colors become effective as expected.

Do you have same problem ? I am on NB 8.1 here.

**Comment by granella** [comment]
@Revivius What’s your theme you were using before installing the new version?

**Comment by Revivius** [comment]
@granella Was using your theme the way it is in your github repo but I think that is irrevelant because screenshot is from 'the IDE that is launched from my IDE' when I run the plugin. I think default theme, in that case, is "NetBeans".

**Comment by granella** [comment]
@Revivius hummm, please click in Restore...

**Comment by Revivius** [comment]
@granella; I had to add another hack to make annotation colors (breakpoint in the above example was one of them) change after setting Darcula theme. It seems to resolve the issue.

I will commit my changes on top of your PR and merge it as we did with @markiewb in PR #12. 

Thank you for the theme, it completes the LAF !

**Comment by granella** [comment]
@Revivius added new changes

**Comment by Revivius** [comment]
@granella  Ups, merged already. Let me see.

**Comment by granella** [comment]
@Revivius I'm trying to mimic most of the IntelliJ Darcula color scheme, that's why I added blue color for program counter lines, but their colors in debugger are best.

Cool!

**Comment by Revivius** [comment]
Cool, remerged. Thank you.

**Pull request closed without merging**
