### PR TITLE
Add icon filter

### PR DESCRIPTION
**Pull request by markiewb**
* use code from o.n.swing.laf.dark
* add option to options panel

Use the icon filter from the dark metal theme. Using this filter is optional. Therefor I updated the options panel
2016-01-26_21h53_43

### CODE REVIEW

**Comment by Revivius** [comment]
@markiewb can you please provide a screen shot of new options panel (I know it is just a checkbox but...) ?

**Comment by markiewb** [comment]
2016-01-26_22h57_02
Here we go

**Comment by Revivius** [comment]
@markiewb merging this with a very small commit on it (as we did in PR #12). Thank you once more !

**Comment by markiewb** [comment]
@Revivius: Can you please mark the merged pull requests with the proper milestone! This one is for v.1.4

**Pull request closed without merging**
